from random import choice

tlas = ["AAB","AAC","AAD","AAE","AAG","AAP","AAT","AAV","AAZ","ABB","ABC","ABD",
"ABE","ABG","ABP","ABT","ABV","ABZ","ACB","ACC","ACD","ACE","ACG","ACP","ACT",
"ACV","ACZ","ADB","ADC","ADD","ADE","ADG","ADP","ADT","ADV","ADZ","AEB","AEC",
"AED","AEE","AEG","AEP","AET","AEV","AEZ","AFB","AFC","AFD","AFE","AFG","AFP",
"AFT","AFV","AFZ","AGB","AGC","AGD","AGE","AGG","AGP","AGT","AGV","AGZ","AHB",
"AHC","AHD","AHE","AHG","AHP","AHT","AHV","AHZ","AIB","AIC","AID","AIE","AIG",
"AIP","AIT","AIV","AIZ","AJB","AJC","AJD","AJE","AJG","AJP","AJT","AJV","AJZ",
"AKB","AKC","AKD","AKE","AKG","AKP","AKT","AKV","ALB","ALC","ALD","ALE","ALG",
"ALP","ALT","ALV","ALZ","AMB","AMC","AMD","AME","AMG","AMP","AMT","AMV","AMZ",
"ANB","ANC","AND","ANE","ANG","ANP","ANT","ANV","ANZ","AOB","AOC","AOD","AOE",
"AOG","AOP","AOT","AOV","AOZ","APB","APC","APD","APE","APG","APP","APT","APV",
"APZ","AQB","AQC","AQG","AQP","AQT","ARB","ARC","ARD","ARE","ARG","ARP","ART",
"ARV","ARZ","ASB","ASC","ASD","ASE","ASG","ASP","AST","ASV","ASZ","ATB","ATC",
"ATD","ATE","ATG","ATP","ATT","ATV","ATZ","AUB","AUC","AUD","AUE","AUG","AUP",
"AUT","AUV","AUZ","AVB","AVC","AVD","AVE","AVG","AVP","AVT","AVV","AVZ","AWB",
"AWC","AWD","AWE","AWG","AWP","AWT","AWV","AWZ","AXB","AXC","AXD","AXE","AXG",
"AXP","AXT","AXV","AYB","AYC","AYD","AYE","AYG","AYP","AYT","AYZ","AZB","AZC",
"AZD","AZE","AZG","AZP","AZT","AZV","AZZ","BAB","BAC","BAD","BAE","BAG","BAP",
"BAT","BAV","BAZ","BBB","BBD","BBE","BBG","BBP","BBT","BBV","BBZ","BCB","BCC",
"BCD","BCE","BCG","BCP","BCT","BCV","BCZ","BDB","BDC","BDD","BDE","BDG","BDP",
"BDT","BDV","BDZ","BEB","BEC","BED","BEE","BEG","BEP","BET","BEV","BEZ","BFB",
"BFC","BFD","BFE","BFG","BFP","BFT","BFV","BFZ","BGB","BGC","BGD","BGE","BGG",
"BGP","BGT","BGV","BGZ","BHB","BHC","BHD","BHE","BHG","BHP","BHT","BHV","BIB",
"BIC","BID","BIE","BIG","BIP","BIT","BIV","BIZ","BJB","BJC","BJD","BJE","BJG",
"BJP","BJT","BJV","BJZ","BKB","BKC","BKD","BKE","BKG","BKP","BKT","BKV","BKZ",
"BLB","BLC","BLD","BLE","BLG","BLP","BLT","BLV","BLZ","BMB","BMC","BMD","BME",
"BMG","BMP","BMT","BMV","BMZ","BNB","BNC","BND","BNE","BNG","BNP","BNT","BNV",
"BNZ","BOB","BOC","BOD","BOE","BOG","BOP","BOT","BOV","BOZ","BPB","BPC","BPD",
"BPE","BPG","BPP","BPT","BPV","BQB","BQC","BQD","BQE","BQG","BQP","BQT","BRB",
"BRC","BRD","BRE","BRG","BRP","BRT","BRV","BRZ","BSB","BSC","BSD","BSE","BSG",
"BSP","BST","BSV","BSZ","BTB","BTC","BTD","BTE","BTG","BTP","BTT","BTV","BTZ",
"BUB","BUC","BUD","BUE","BUG","BUP","BUT","BUV","BUZ","BVB","BVC","BVD","BVE",
"BVG","BVP","BVT","BVV","BVZ","BWB","BWC","BWD","BWE","BWG","BWP","BWT","BWV",
"BWZ","BXB","BXC","BXD","BXE","BXG","BXP","BXT","BYB","BYC","BYD","BYG","BYP",
"BYT","BYV","BZB","BZC","BZD","BZE","BZG","BZP","BZT","BZV","BZZ","CAB","CAC",
"CAD","CAE","CAG","CAP","CAT","CAV","CAZ","CBB","CBC","CBD","CBE","CBG","CBP",
"CBT","CBV","CBZ","CCB","CCC","CCD","CCE","CCG","CCP","CCT","CCV","CCZ","CDB",
"CDC","CDD","CDE","CDG","CDP","CDT","CDV","CDZ","CEB","CEC","CED","CEE","CEG",
"CEP","CET","CEV","CEZ","CFB","CFC","CFD","CFE","CFG","CFP","CFT","CFV","CFZ",
"CGB","CGC","CGD","CGE","CGG","CGP","CGT","CGV","CGZ","CHB","CHC","CHD","CHE",
"CHG","CHP","CHT","CHV","CHZ","CIB","CIC","CID","CIE","CIG","CIP","CIT","CIV",
"CJB","CJC","CJD","CJE","CJG","CJP","CJT","CJV","CJZ","CKB","CKC","CKD","CKE",
"CKG","CKP","CKT","CKV","CKZ","CLB","CLC","CLD","CLE","CLG","CLP","CLT","CLV",
"CLZ","CMB","CMC","CMD","CME","CMG","CMP","CMT","CMV","CMZ","CNB","CNC","CND",
"CNE","CNG","CNP","CNT","CNV","CNZ","COB","COC","COD","COE","COG","COP","COT",
"COV","COZ","CPB","CPC","CPD","CPE","CPG","CPP","CPT","CPV","CPZ","CQB","CQC",
"CQD","CQE","CQG","CQT","CRB","CRC","CRD","CRE","CRG","CRP","CRT","CRV","CRZ",
"CSB","CSC","CSD","CSE","CSG","CSP","CST","CSV","CSZ","CTB","CTC","CTD","CTE",
"CTG","CTP","CTT","CTV","CTZ","CUB","CUC","CUD","CUE","CUG","CUP","CUT","CUV",
"CUZ","CVB","CVC","CVD","CVE","CVG","CVP","CVT","CVV","CVZ","CWB","CWC","CWD",
"CWE","CWG","CWP","CWT","CWV","CXB","CXC","CXD","CXP","CXT","CXV","CYB","CYC",
"CYD","CYE","CYG","CYP","CYT","CYV","CYZ","CZC","CZD","CZE","CZG","CZP","CZT",
"DAB","DAC","DAD","DAE","DAG","DAP","DAT","DAV","DAZ","DBB","DBC","DBD","DBE",
"DBG","DBP","DBT","DBV","DBZ","DCB","DCC","DCD","DCE","DCG","DCP","DCT","DCV",
"DCZ","DDB","DDC","DDD","DDE","DDG","DDP","DDT","DDV","DDZ","DEB","DEC","DED",
"DEE","DEG","DEP","DET","DEV","DEZ","DFB","DFC","DFD","DFE","DFG","DFP","DFT",
"DFV","DFZ","DGB","DGC","DGD","DGE","DGG","DGP","DGT","DGV","DGZ","DHB","DHC",
"DHD","DHE","DHG","DHP","DHT","DHV","DHZ","DIB","DIC","DID","DIE","DIG","DIP",
"DIT","DIV","DIZ","DJB","DJC","DJD","DJE","DJG","DJP","DJT","DJV","DKB","DKC",
"DKD","DKE","DKG","DKP","DKT","DKV","DKZ","DLB","DLC","DLD","DLE","DLG","DLP",
"DLT","DLV","DLZ","DMB","DMC","DMD","DME","DMG","DMP","DMT","DMV","DMZ","DNB",
"DNC","DND","DNE","DNG","DNP","DNT","DNV","DNZ","DOB","DOC","DOD","DOE","DOG",
"DOP","DOT","DOV","DOZ","DPB","DPC","DPD","DPE","DPG","DPP","DPT","DPV","DPZ",
"DQE","DQP","DQT","DQV","DRB","DRC","DRD","DRE","DRG","DRP","DRT","DRV","DRZ",
"DSB","DSC","DSD","DSE","DSG","DSP","DST","DSV","DSZ","DTB","DTC","DTD","DTE",
"DTG","DTP","DTT","DTV","DTZ","DUB","DUC","DUD","DUE","DUG","DUP","DUT","DUV",
"DVB","DVC","DVD","DVE","DVG","DVP","DVT","DVV","DWB","DWC","DWD","DWE","DWG",
"DWP","DWT","DWV","DWZ","DXB","DXC","DXD","DXP","DXT","DXV","DXZ","DYC","DYD",
"DYE","DYG","DYP","DYT","DZB","DZC","DZD","DZG","DZP","DZZ","EAB","EAC","EAD",
"EAE","EAG","EAP","EAT","EAV","EAZ","EBB","EBC","EBD","EBE","EBG","EBP","EBT",
"EBV","ECB","ECC","ECD","ECE","ECG","ECP","ECT","ECV","EDB","EDC","EDD","EDE",
"EDG","EDP","EDT","EDV","EEB","EEC","EED","EEE","EEG","EEP","EET","EEV","EEZ",
"EFB","EFC","EFD","EFE","EFG","EFP","EFT","EFV","EFZ","EGB","EGC","EGD","EGE",
"EGG","EGP","EGT","EGV","EGZ","EHB","EHC","EHD","EHE","EHG","EHP","EHT","EHV",
"EIB","EIC","EID","EIE","EIG","EIP","EIT","EIV","EJB","EJC","EJD","EJE","EJG",
"EJP","EJT","EJV","EKB","EKC","EKD","EKE","EKG","EKP","EKT","EKV","ELB","ELC",
"ELD","ELE","ELG","ELP","ELT","ELV","EMB","EMC","EMD","EME","EMG","EMP","EMT",
"EMV","EMZ","ENB","ENC","END","ENE","ENG","ENP","ENT","ENV","ENZ","EOB","EOC",
"EOD","EOE","EOG","EOP","EOT","EPB","EPC","EPD","EPE","EPG","EPP","EPT","EPV",
"EPZ","EQB","EQC","EQE","EQG","EQP","EQT","EQV","ERB","ERC","ERD","ERE","ERG",
"ERP","ERT","ERV","ESB","ESC","ESD","ESE","ESG","ESP","EST","ESV","ESZ","ETB",
"ETC","ETD","ETE","ETG","ETP","ETT","ETV","ETZ","EUB","EUC","EUD","EUE","EUG",
"EUP","EUT","EUV","EVB","EVC","EVD","EVE","EVG","EVP","EVT","EVV","EVZ","EWB",
"EWC","EWD","EWE","EWG","EWP","EWT","EWV","EXC","EXD","EXE","EXP","EXT","EYC",
"EYD","EYE","EYP","EYT","EZE","FAB","FAC","FAD","FAE","FAG","FAP","FAT","FAV",
"FAZ","FBB","FBC","FBD","FBE","FBG","FBP","FBT","FBZ","FCB","FCC","FCD","FCE",
"FCG","FCP","FCT","FCV","FCZ","FDB","FDC","FDD","FDE","FDG","FDP","FDT","FDV",
"FEB","FEC","FED","FEE","FEG","FEP","FET","FEV","FEZ","FFB","FFC","FFD","FFE",
"FFG","FFP","FFT","FFV","FGB","FGC","FGD","FGE","FGG","FGP","FGT","FGV","FHB",
"FHC","FHD","FHE","FHG","FHP","FHT","FHV","FIB","FIC","FID","FIE","FIG","FIP",
"FIT","FIV","FJB","FJC","FJD","FJG","FJP","FKB","FKC","FKD","FKG","FKP","FKT",
"FLB","FLC","FLD","FLE","FLG","FLP","FLT","FLV","FMB","FMC","FMD","FME","FMG",
"FMP","FMV","FMZ","FNB","FNC","FND","FNE","FNG","FNP","FNT","FNV","FNZ","FOB",
"FOC","FOD","FOE","FOG","FOP","FOT","FOV","FPB","FPC","FPD","FPE","FPG","FPP",
"FPT","FPV","FPZ","FQP","FRB","FRC","FRD","FRE","FRG","FRP","FRT","FRV","FSB",
"FSC","FSD","FSE","FSG","FSP","FST","FSV","FSZ","FTB","FTC","FTD","FTE","FTG",
"FTP","FTT","FTV","FTZ","FUB","FUC","FUD","FUE","FUG","FUP","FUT","FVC","FVD",
"FVE","FVG","FVP","FVT","FWB","FWC","FWD","FWE","FWG","FWP","FWT","FWZ","FXB",
"FXC","FXE","FXG","FXP","FXT","FXV","FXZ","FYB","FYC","FYD","FYE","FYG","FYP",
"FZC","FZD","FZE","FZZ","GAB","GAC","GAD","GAE","GAG","GAP","GAT","GAV","GAZ",
"GBB","GBC","GBD","GBE","GBG","GBP","GBT","GBV","GBZ","GCB","GCC","GCD","GCE",
"GCG","GCP","GCT","GCV","GCZ","GDB","GDC","GDD","GDE","GDG","GDP","GDT","GDV",
"GDZ","GEB","GEC","GED","GEE","GEG","GEP","GET","GEV","GEZ","GFB","GFC","GFD",
"GFE","GFG","GFP","GFT","GFZ","GGB","GGC","GGD","GGE","GGG","GGP","GGT","GGV",
"GGZ","GHB","GHC","GHD","GHE","GHG","GHP","GHT","GHV","GHZ","GIB","GIC","GID",
"GIE","GIG","GIP","GIT","GIZ","GJC","GJD","GJE","GJG","GJP","GJT","GKB","GKC",
"GKD","GKG","GKP","GKT","GKV","GKZ","GLB","GLC","GLD","GLE","GLG","GLP","GLT",
"GLV","GLZ","GMB","GMC","GMD","GME","GMG","GMP","GMT","GMV","GMZ","GNB","GNC",
"GND","GNE","GNG","GNP","GNT","GNV","GNZ","GOB","GOC","GOD","GOE","GOG","GOP",
"GOT","GOV","GOZ","GPB","GPC","GPD","GPE","GPG","GPP","GPT","GPV","GPZ","GQG",
"GQT","GRB","GRC","GRD","GRE","GRG","GRP","GRT","GRV","GRZ","GSB","GSC","GSD",
"GSE","GSG","GSP","GST","GSV","GSZ","GTB","GTC","GTD","GTE","GTG","GTP","GTT",
"GTV","GTZ","GUB","GUC","GUD","GUE","GUG","GUP","GUT","GUV","GVB","GVC","GVD",
"GVE","GVG","GVP","GVT","GWB","GWC","GWD","GWE","GWG","GWP","GWT","GXE","GXG",
"GXP","GXT","GYB","GYC","GYD","GYE","GYG","GYP","GZP","GZT","HAB","HAC","HAD",
"HAE","HAG","HAP","HAT","HAV","HAZ","HBB","HBC","HBD","HBE","HBG","HBP","HBT",
"HBV","HBZ","HCB","HCC","HCD","HCE","HCG","HCP","HCT","HCV","HCZ","HDB","HDC",
"HDD","HDE","HDG","HDP","HDT","HDV","HDZ","HEB","HEC","HED","HEE","HEG","HEP",
"HET","HEV","HFB","HFC","HFD","HFE","HFG","HFP","HFT","HFV","HGB","HGC","HGD",
"HGE","HGG","HGP","HGT","HGV","HHB","HHC","HHD","HHE","HHG","HHP","HHT","HHV",
"HIB","HIC","HID","HIE","HIG","HIP","HIT","HIV","HJB","HJC","HJD","HJE","HJG",
"HJP","HJT","HJV","HKB","HKC","HKD","HKE","HKG","HKP","HKT","HLB","HLC","HLD",
"HLE","HLG","HLP","HLT","HLV","HLZ","HMB","HMC","HMD","HME","HMG","HMP","HMT",
"HMV","HNB","HNC","HND","HNE","HNG","HNP","HNT","HNV","HNZ","HOB","HOC","HOD",
"HOE","HOG","HOP","HOT","HOV","HPB","HPC","HPD","HPE","HPG","HPP","HPT","HPV",
"HQC","HQE","HQG","HQT","HQZ","HRB","HRC","HRD","HRE","HRG","HRP","HRT","HRV",
"HRZ","HSB","HSC","HSD","HSE","HSG","HSP","HST","HSV","HTB","HTC","HTD","HTE",
"HTG","HTP","HTT","HTV","HTZ","HUB","HUC","HUD","HUE","HUG","HUP","HUT","HUV",
"HUZ","HVB","HVC","HVD","HVG","HVP","HVT","HVV","HVZ","HWB","HWC","HWD","HWE",
"HWG","HWP","HWT","HWV","HWZ","HXB","HXC","HXD","HYB","HYC","HYD","HYE","HYP",
"HYT","HZB","HZD","HZG","HZT","IAB","IAC","IAD","IAE","IAG","IAP","IAT","IAV",
"IBB","IBC","IBD","IBE","IBG","IBP","IBT","IBV","IBZ","ICB","ICC","ICD","ICE",
"ICG","ICP","ICT","ICV","ICZ","IDB","IDC","IDD","IDE","IDG","IDP","IDT","IDV",
"IEB","IEC","IED","IEE","IEG","IEP","IET","IEV","IFB","IFC","IFD","IFE","IFG",
"IFP","IFT","IFV","IFZ","IGB","IGC","IGD","IGE","IGG","IGP","IGT","IGV","IHB",
"IHC","IHD","IHE","IHG","IHP","IHT","IHV","IIB","IIC","IID","IIE","IIG","IIP",
"IIT","IJB","IJC","IJD","IJG","IJP","IJT","IJV","IKB","IKC","IKD","IKE","IKG",
"IKP","IKT","IKV","IKZ","ILB","ILC","ILD","ILE","ILG","ILP","ILT","ILV","ILZ",
"IMB","IMC","IMD","IME","IMG","IMP","IMT","IMV","IMZ","INB","INC","IND","INE",
"ING","INP","INT","INV","INZ","IOB","IOC","IOD","IOE","IOG","IOP","IOT","IOV",
"IOZ","IPB","IPC","IPD","IPE","IPG","IPP","IPT","IPV","IQC","IQD","IQE","IQP",
"IQT","IQV","IRB","IRC","IRD","IRE","IRG","IRP","IRT","IRV","IRZ","ISB","ISC",
"ISD","ISE","ISG","ISP","IST","ISV","ITB","ITC","ITD","ITE","ITG","ITP","ITT",
"ITV","IUB","IUC","IUD","IUE","IUG","IUP","IUT","IUV","IVB","IVC","IVD","IVE",
"IVG","IVP","IVT","IVV","IVZ","IWB","IWC","IWD","IWE","IWG","IWP","IWT","IWV",
"IWZ","IXB","IXC","IXD","IXE","IXG","IXP","IXT","IXV","IXZ","IYB","IYC","IYD",
"IYE","IYP","IYT","IZB","IZE","IZZ","JAB","JAC","JAD","JAE","JAG","JAP","JAT",
"JAV","JAZ","JBB","JBC","JBD","JBG","JBT","JBV","JBZ","JCB","JCC","JCD","JCE",
"JCG","JCP","JCT","JCV","JDB","JDC","JDD","JDE","JDP","JDT","JDV","JDZ","JEB",
"JEC","JED","JEE","JEG","JEP","JET","JEV","JFB","JFC","JFD","JFE","JFG","JFP",
"JFT","JGB","JGC","JGE","JGP","JGT","JGV","JHB","JHC","JHD","JHE","JHG","JHP",
"JHT","JHV","JHZ","JIB","JIC","JID","JIE","JIG","JIT","JJB","JJC","JJG","JJT",
"JKB","JKC","JKD","JKG","JKP","JKT","JKV","JLB","JLC","JLD","JLE","JLG","JLP",
"JLT","JLZ","JMB","JMC","JMD","JME","JMG","JMP","JMT","JMV","JNB","JNC","JND",
"JNE","JNG","JNP","JNT","JNV","JNZ","JOB","JOC","JOD","JOE","JOG","JOP","JOT",
"JOZ","JPB","JPC","JPD","JPE","JPG","JPP","JPT","JPV","JPZ","JQT","JRB","JRC",
"JRD","JRE","JRG","JRP","JRT","JRV","JRZ","JSB","JSC","JSD","JSE","JSG","JSP",
"JST","JSV","JTB","JTC","JTD","JTE","JTG","JTP","JTT","JTV","JUB","JUD","JUP",
"JUT","JUV","JUZ","JVB","JVC","JVD","JVG","JVP","JVT","JWB","JWC","JWE","JWG",
"JWP","JWT","JWV","JWZ","JXB","JXD","JYB","JYC","JYD","JYP","JYV","JZD","KAB",
"KAC","KAD","KAE","KAG","KAP","KAT","KAV","KAZ","KBB","KBC","KBD","KBE","KBG",
"KBP","KBT","KBV","KBZ","KCB","KCC","KCD","KCE","KCG","KCP","KCT","KCV","KCZ",
"KDB","KDC","KDD","KDE","KDG","KDP","KDT","KDV","KEB","KEC","KED","KEE","KEP","KET","KEV","KFB","KFC","KFD","KFG","KFP","KFT","KGB","KGC","KGD","KGG","KGP","KGT","KGV","KGZ","KHB","KHC","KHD","KHG","KHP","KHT","KHV","KHZ","KIB","KIC","KID","KIE","KIG","KIP","KIT","KIV","KIZ","KJB","KJC","KJE","KJP","KJV","KKB","KKC","KKD","KKE","KKG","KKP","KKT","KKV","KLB","KLC","KLD","KLE","KLG","KLP","KLT","KLV","KLZ","KMB","KMC","KMD","KME","KMG","KMP","KMT","KMV","KMZ","KNB","KNC","KND","KNE","KNG","KNP","KNT","KNZ","KOB","KOC","KOD","KOE","KOG","KOP","KOT","KOV","KOZ","KPB","KPC","KPD","KPE","KPP","KPT","KPV","KPZ","KQV","KQZ","KRB","KRC","KRD","KRE","KRG","KRP","KRT","KRV","KRZ","KSB","KSC","KSD","KSE","KSG","KSP","KST","KSV","KSZ","KTB","KTC","KTD","KTE","KTG","KTP","KTT","KTV","KTZ","KUB","KUC","KUD","KUG","KUT","KUV","KVB","KVC","KVD","KVE","KVG","KVP","KVV","KWB","KWC","KWD","KWE","KWG","KWP","KWT","KWV","KWZ","KXC","KXD","KXP","KXT","KYC","KYD","KYE","KYP","KYT","KYV","KYZ","KZB","KZC","KZT","LAB","LAC","LAD","LAE","LAG","LAP","LAT","LAV","LAZ","LBB","LBC","LBD","LBE","LBG","LBP","LBT","LBV","LBZ","LCB","LCC","LCD","LCE","LCG","LCP","LCT","LCV","LDB","LDC","LDD","LDE","LDG","LDP","LDT","LDV","LEB","LEC","LED","LEE","LEG","LEP","LET","LEV","LEZ","LFB","LFC","LFD","LFE","LFG","LFP","LFT","LFV","LFZ","LGB","LGC","LGD","LGE","LGG","LGP","LGT","LGV","LHB","LHC","LHD","LHE","LHG","LHP","LHT","LHV","LIB","LIC","LID","LIE","LIG","LIP","LIT","LIV","LIZ","LJC","LJD","LJG","LJP","LKB","LKD","LKE","LKG","LKP","LKV","LKZ","LLB","LLC","LLD","LLE","LLG","LLP","LLT","LLV","LLZ","LMB","LMC","LMD","LME","LMG","LMP","LMT","LMV","LMZ","LNB","LNC","LND","LNE","LNG","LNP","LNT","LNV","LNZ","LOB","LOC","LOD","LOE","LOG","LOP","LOT","LOV","LOZ","LPB","LPC","LPD","LPE","LPG","LPP","LPT","LPV","LPZ","LQC","LQG","LQP","LQT","LRB","LRC","LRD","LRE","LRG","LRP","LRT","LRV","LRZ","LSB","LSC","LSD","LSE","LSG","LSP","LST","LSV","LSZ","LTB","LTC","LTD","LTE","LTG","LTP","LTT","LTV","LTZ","LUB","LUC","LUD","LUE","LUG","LUP","LUT","LUV","LUZ","LVB","LVC","LVD","LVG","LVP","LVT","LVV","LVZ","LWB","LWC","LWD","LWE","LWG","LWP","LWT","LWV","LXC","LXD","LXG","LXT","LXV","LYB","LYC","LYD","LYE","LYG","LYP","LYZ","LZB","LZC","LZD","LZE","LZG","LZP","LZT","MAB","MAC","MAD","MAE","MAG","MAP","MAT","MAV","MAZ","MBB","MBC","MBD","MBE","MBG","MBP","MBT","MBV","MBZ","MCB","MCC","MCD","MCE","MCG","MCP","MCT","MCV","MCZ","MDB","MDC","MDD","MDE","MDG","MDP","MDT","MDV","MDZ","MEB","MEC","MED","MEE","MEG","MEP","MET","MEV","MEZ","MFB","MFC","MFD","MFE","MFG","MFP","MFT","MFV","MFZ","MGB","MGC","MGD","MGE","MGG","MGP","MGT","MGV","MGZ","MHB","MHC","MHD","MHE","MHG","MHP","MHT","MHV","MHZ","MIB","MIC","MID","MIE","MIG","MIP","MIT","MIV","MIZ","MJB","MJC","MJD","MJE","MJG","MJP","MJT","MJV","MKB","MKC","MKD","MKE","MKG","MKP","MKT","MKV","MKZ","MLB","MLC","MLD","MLE","MLG","MLP","MLT","MLV","MLZ","MMB","MMC","MMD","MME","MMG","MMP","MMT","MMV","MMZ","MNB","MNC","MND","MNE","MNG","MNP","MNT","MNZ","MOB","MOC","MOD","MOE","MOG","MOP","MOT","MOV","MOZ","MPB","MPC","MPD","MPE","MPG","MPP","MPT","MPV","MPZ","MQB","MQC","MQD","MQG","MQP","MQT","MQV","MQZ","MRB","MRC","MRD","MRE","MRG","MRP","MRT","MRV","MRZ","MSB","MSC","MSD","MSE","MSG","MSP","MST","MSV","MSZ","MTB","MTC","MTD","MTE","MTG","MTP","MTT","MTV","MTZ","MUB","MUC","MUD","MUE","MUG","MUP","MUT","MUV","MUZ","MVB","MVC","MVD","MVE","MVG","MVP","MVT","MVV","MVZ","MWB","MWC","MWD","MWE","MWG","MWP","MWT","MWV","MWZ","MXC","MXE","MXP","MXT","MXV","MXZ","MYB","MYC","MYD","MYE","MYP","MYT","MYV","MZB","MZC","MZP","MZT","MZZ","NAB","NAC","NAD","NAE","NAG","NAP","NAT","NAV","NBB","NBC","NBD","NBE","NBG","NBP","NBT","NBV","NCB","NCC","NCD","NCE","NCG","NCP","NCT","NCV","NDB","NDC","NDD","NDE","NDG","NDP","NDT","NDV","NDZ","NEB","NEC","NED","NEE","NEG","NEP","NET","NEV","NEZ","NFB","NFC","NFD","NFE","NFG","NFP","NFT","NFV","NFZ","NGB","NGC","NGD","NGE","NGG","NGP","NGT","NGV","NGZ","NHB","NHC","NHD","NHE","NHG","NHP","NHT","NHV","NHZ","NIB","NIC","NID","NIE","NIG","NIP","NIT","NIV","NJB","NJC","NJD","NJP","NJT","NKB","NKC","NKD","NKE","NKG","NKP","NKT","NKV","NLB","NLC","NLD","NLE","NLG","NLP","NLT","NLV","NLZ","NMB","NMC","NMD","NME","NMG","NMP","NMT","NMV","NMZ","NNB","NNC","NND","NNE","NNG","NNP","NNT","NNV","NNZ","NOB","NOC","NOD","NOE","NOG","NOP","NOT","NOV","NPB","NPC","NPD","NPE","NPG","NPP","NPT","NPV","NPZ","NQB","NQC","NQT","NRB","NRC","NRD","NRE","NRG","NRP","NRT","NRV","NRZ","NSB","NSC","NSD","NSE","NSG","NSP","NST","NSV","NSZ","NTB","NTC","NTD","NTE","NTG","NTP","NTT","NTV","NTZ","NUB","NUC","NUD","NUE","NUG","NUP","NUT","NUV","NVB","NVC","NVD","NVE","NVG","NVP","NVT","NVV","NVZ","NWB","NWC","NWD","NWE","NWG","NWP","NWT","NXC","NXD","NXE","NXG","NXP","NXT","NXV","NYC","NYE","NYG","NYP","NYT","NZB","NZC","NZD","NZE","NZG","NZP","NZT","NZZ","OAB","OAC","OAD","OAE","OAG","OAP","OAT","OAV","OBB","OBC","OBD","OBE","OBG","OBP","OBT","OBV","OBZ","OCB","OCC","OCD","OCE","OCG","OCP","OCT","OCV","OCZ","ODB","ODC","ODD","ODE","ODG","ODP","ODT","ODV","OEB","OEC","OED","OEE","OEG","OEP","OET","OFB","OFC","OFD","OFE","OFG","OFP","OFT","OFV","OFZ","OGB","OGC","OGD","OGE","OGG","OGP","OGT","OGV","OGZ","OHB","OHC","OHD","OHE","OHG","OHP","OHT","OHV","OIB","OIC","OID","OIE","OIG","OIP","OIT","OIV","OJB","OJC","OJD","OJE","OJP","OJT","OKB","OKC","OKD","OKE","OKG","OKP","OLB","OLC","OLD","OLE","OLG","OLP","OLT","OLV","OMB","OMC","OMD","OME","OMG","OMP","OMT","OMV","OMZ","ONB","ONC","OND","ONE","ONG","ONP","ONT","ONV","ONZ","OOB","OOC","OOD","OOE","OOP","OOT","OOV","OOZ","OPB","OPC","OPD","OPE","OPG","OPP","OPT","OPV","OPZ","ORB","ORC","ORD","ORE","ORG","ORP","ORT","ORV","OSB","OSC","OSD","OSE","OSG","OSP","OST","OSV","OTB","OTC","OTD","OTE","OTG","OTP","OTT","OTV","OTZ","OUB","OUC","OUD","OUP","OUT","OVB","OVC","OVD","OVE","OVG","OVP","OVT","OVV","OWB","OWC","OWD","OWG","OWP","OWT","OXB","OXC","OXE","OXT","OYC","OYE","OYP","OYT","OZB","OZT","OZZ","PAB","PAC","PAD","PAE","PAG","PAP","PAT","PAV","PAZ","PBB","PBC","PBD","PBE","PBG","PBP","PBT","PBZ","PCB","PCC","PCD","PCE","PCG","PCP","PCT","PCV","PCZ","PDB","PDC","PDD","PDE","PDG","PDP","PDT","PDV","PDZ","PEB","PEC","PED","PEE","PEG","PEP","PET","PEV","PEZ","PFB","PFC","PFD","PFE","PFG","PFP","PFT","PFV","PGB","PGC","PGD","PGE","PGG","PGP","PGT","PGV","PHB","PHC","PHD","PHE","PHG","PHP","PHT","PHV","PIB","PIC","PID","PIE","PIG","PIP","PIT","PIV","PJB","PJC","PJD","PJG","PJP","PJV","PKB","PKC","PKD","PKE","PKG","PKP","PKT","PKV","PLB","PLC","PLD","PLE","PLG","PLP","PLT","PLV","PLZ","PMB","PMC","PMD","PME","PMG","PMP","PMT","PMV","PMZ","PNB","PNC","PND","PNE","PNG","PNP","PNT","PNV","PNZ","POB","POC","POD","POE","POG","POP","POT","POV","POZ","PPB","PPC","PPD","PPE","PPG","PPP","PPT","PPV","PQC","PRB","PRC","PRD","PRE","PRG","PRP","PRT","PRV","PRZ","PSB","PSC","PSD","PSE","PSG","PSP","PST","PSV","PTB","PTC","PTD","PTE","PTG","PTP","PTT","PTV","PTZ","PUB","PUC","PUD","PUE","PUP","PUT","PUZ","PVB","PVC","PVD","PVE","PVG","PVP","PVT","PVV","PVZ","PWB","PWC","PWD","PWE","PWG","PWP","PWT","PWV","PXC","PXE","PXG","PXT","PYB","PYC","PYD","PYG","PYT","PZB","PZC","PZE","PZP","PZT","QAB","QAC","QAD","QAG","QAP","QAT","QBC","QBD","QBE","QBP","QBZ","QCC","QCD","QCP","QCT","QDB","QDE","QDT","QEC","QED","QEE","QEP","QFB","QFC","QFD","QFE","QFG","QFP","QFT","QFZ","QGC","QGD","QGP","QHC","QHD","QHE","QHP","QHZ","QIB","QIC","QID","QIP","QIT","QIZ","QJE","QKD","QLD","QLP","QLT","QMC","QMD","QME","QMG","QMP","QMT","QMV","QNB","QNC","QND","QNE","QNT","QOD","QPC","QPD","QPE","QPP","QPT","QPV","QQP","QQT","QRB","QRC","QRD","QRE","QRG","QRP","QRT","QRZ","QSB","QSC","QSD","QSP","QST","QTC","QTD","QTE","QTG","QTP","QTT","QTV","QTZ","QUB","QUC","QUE","QUG","QUP","QUT","QVB","QVC","QVD","QVE","QVT","QWC","QWP","QWV","QXC","QXE","QYC","QYT","QZE","RAB","RAC","RAD","RAE","RAG","RAP","RAT","RAV","RBB","RBC","RBD","RBE","RBG","RBP","RBT","RBV","RBZ","RCB","RCC","RCD","RCE","RCG","RCP","RCT","RCV","RCZ","RDB","RDC","RDD","RDE","RDG","RDP","RDT","RDV","RDZ","REB","REC","RED","REE","REG","REP","RET","REV","REZ","RFB","RFC","RFD","RFE","RFG","RFP","RFT","RFV","RGB","RGC","RGD","RGE","RGG","RGP","RGT","RGV","RHB","RHC","RHD","RHE","RHG","RHP","RHT","RHV","RIB","RIC","RID","RIE","RIP","RIT","RIV","RJB","RJC","RJD","RJE","RJP","RJV","RKB","RKC","RKD","RKE","RKG","RKP","RKT","RKV","RKZ","RLB","RLC","RLD","RLE","RLG","RLP","RLT","RLV","RLZ","RMB","RMC","RMD","RME","RMG","RMP","RMT","RMV","RNB","RNC","RND","RNE","RNG","RNP","RNT","RNV","RNZ","ROB","ROC","ROD","ROE","ROG","ROP","ROT","ROV","RPB","RPC","RPD","RPE","RPG","RPP","RPT","RPV","RPZ","RQB","RQC","RQD","RQE","RRB","RRC","RRD","RRE","RRG","RRP","RRT","RRV","RSB","RSC","RSD","RSE","RSG","RSP","RST","RSV","RTB","RTC","RTD","RTE","RTG","RTP","RTT","RTV","RTZ","RUB","RUC","RUE","RUG","RUP","RUT","RUV","RVB","RVC","RVD","RVE","RVG","RVP","RVT","RVV","RWB","RWC","RWD","RWE","RWP","RWT","RXE","RXP","RYB","RYC","RYE","RYG","RYZ","RZB","RZC","RZD","RZE","SAB","SAC","SAD","SAE","SAG","SAP","SAT","SAV","SAZ","SBB","SBC","SBD","SBE","SBG","SBP","SBT","SBV","SBZ","SCB","SCC","SCD","SCE","SCG","SCP","SCT","SCV","SCZ","SDB","SDC","SDD","SDE","SDG","SDP","SDT","SDV","SDZ","SEB","SEC","SED","SEE","SEG","SEP","SET","SEV","SEZ","SFB","SFC","SFD","SFE","SFG","SFP","SFT","SFV","SFZ","SGB","SGC","SGD","SGE","SGG","SGP","SGT","SGV","SGZ","SHB","SHC","SHD","SHE","SHG","SHP","SHT","SHV","SIB","SIC","SID","SIE","SIG","SIP","SIT","SIV","SJB","SJC","SJD","SJE","SJG","SJP","SJT","SJV","SJZ","SKB","SKC","SKD","SKE","SKG","SKP","SKT","SKV","SKZ","SLB","SLC","SLD","SLE","SLG","SLP","SLT","SLV","SMB","SMC","SMD","SME","SMG","SMP","SMT","SMV","SMZ","SNB","SNC","SND","SNE","SNG","SNP","SNT","SNV","SNZ","SOB","SOC","SOD","SOE","SOG","SOP","SOT","SOV","SOZ","SPB","SPC","SPD","SPE","SPG","SPP","SPT","SPV","SPZ","SQP","SQT","SQZ","SRB","SRC","SRD","SRE","SRG","SRP","SRT","SRV","SRZ","SSB","SSC","SSD","SSE","SSG","SSP","SST","SSV","SSZ","STB","STC","STD","STE","STG","STP","STT","STV","STZ","SUB","SUC","SUD","SUE","SUG","SUP","SUT","SUV","SVB","SVC","SVD","SVE","SVG","SVP","SVT","SVV","SVZ","SWB","SWC","SWD","SWE","SWG","SWP","SWT","SWV","SWZ","SXB","SXC","SXD","SXE","SXG","SXT","SXV","SYB","SYC","SYD","SYE","SYG","SYP","SYT","SZB","SZC","SZD","SZE","SZG","SZP","SZT","SZV","SZZ","TAB","TAC","TAD","TAE","TAG","TAP","TAT","TAV","TAZ","TBB","TBC","TBD","TBE","TBG","TBP","TBT","TBV","TBZ","TCB","TCC","TCD","TCE","TCG","TCP","TCT","TCV","TCZ","TDB","TDC","TDD","TDE","TDG","TDP","TDT","TDV","TEB","TEC","TED","TEE","TEG","TEP","TET","TEV","TEZ","TFB","TFC","TFD","TFE","TFG","TFP","TFT","TGB","TGC","TGD","TGE","TGG","TGP","TGT","TGV","TGZ","THB","THC","THD","THE","THG","THP","THT","THV","THZ","TIB","TIC","TID","TIE","TIG","TIP","TIT","TIV","TJB","TJC","TJD","TJP","TKB","TKC","TKD","TKE","TKG","TKP","TKT","TKV","TKZ","TLB","TLC","TLD","TLE","TLG","TLP","TLT","TLV","TLZ","TMB","TMC","TMD","TME","TMG","TMP","TMT","TMV","TMZ","TNB","TNC","TND","TNE","TNG","TNP","TNT","TNV","TNZ","TOB","TOC","TOD","TOE","TOG","TOP","TOT","TOV","TOZ","TPB","TPC","TPD","TPE","TPG","TPP","TPT","TPV","TPZ","TQC","TQE","TQP","TRB","TRC","TRD","TRE","TRG","TRP","TRT","TRV","TRZ","TSB","TSC","TSD","TSE","TSG","TSP","TST","TSV","TSZ","TTB","TTC","TTD","TTE","TTG","TTP","TTT","TTV","TTZ","TUB","TUC","TUD","TUE","TUG","TUP","TUT","TUV","TVB","TVC","TVD","TVE","TVG","TVP","TVT","TVV","TVZ","TWB","TWC","TWD","TWE","TWG","TWP","TWT","TWV","TXC","TXE","TXT","TXV","TYB","TYC","TYD","TYG","TYP","TYT","TZB","TZC","TZD","TZV","UAB","UAC","UAD","UAE","UAG","UAP","UAT","UAV","UAZ","UBB","UBC","UBD","UBE","UBP","UBT","UBV","UCB","UCC","UCD","UCE","UCG","UCP","UCT","UCV","UDB","UDC","UDD","UDE","UDG","UDP","UDT","UDV","UEB","UEC","UED","UEE","UEG","UEP","UET","UEV","UFC","UFD","UFE","UFG","UFP","UFT","UFV","UGB","UGC","UGE","UGG","UGP","UGT","UGV","UHB","UHC","UHD","UHE","UHP","UHT","UHV","UIB","UIC","UID","UIP","UIT","UJC","UJD","UJT","UKB","UKC","UKD","UKG","UKP","UKT","UKZ","ULB","ULC","ULD","ULE","ULG","ULP","ULT","ULV","UMB","UMC","UMD","UMG","UMP","UMT","UMZ","UNB","UNC","UND","UNE","UNG","UNP","UNT","UNV","UOB","UOC","UOD","UOE","UOG","UOP","UOT","UOV","UPB","UPC","UPD","UPE","UPG","UPP","UPT","UPV","UPZ","UQP","URB","URC","URD","URE","URG","URP","URT","URV","USB","USC","USD","USE","USG","USP","UST","USV","UTB","UTC","UTD","UTE","UTG","UTP","UTT","UTV","UTZ","UUC","UUE","UUG","UUP","UUV","UVB","UVC","UVD","UVG","UVP","UVV","UWB","UWC","UWE","UWG","UWP","UWT","UXB","UXC","UXD","UXG","UXT","UYC","UYD","UYT","UZB","UZZ","VAB","VAC","VAD","VAE","VAG","VAP","VAT","VAV","VAZ","VBB","VBC","VBD","VBE","VBG","VBP","VBT","VBV","VBZ","VCB","VCC","VCD","VCE","VCG","VCP","VCT","VCV","VDB","VDC","VDD","VDE","VDG","VDP","VDT","VDV","VEB","VEC","VED","VEE","VEG","VEP","VET","VEV","VFB","VFC","VFD","VFE","VFG","VFP","VFT","VFV","VGB","VGC","VGE","VGG","VGP","VGT","VGZ","VHB","VHC","VHD","VHE","VHP","VIB","VIC","VID","VIE","VIP","VIT","VIV","VIZ","VJC","VKB","VKC","VKG","VKT","VKV","VLB","VLC","VLD","VLE","VLG","VLP","VLT","VLV","VMB","VMC","VMD","VME","VMG","VMP","VMT","VNB","VNC","VND","VNE","VNG","VNP","VNT","VNV","VNZ","VOB","VOC","VOD","VOE","VOG","VOP","VOT","VOV","VOZ","VPB","VPC","VPD","VPP","VPT","VQP","VRB","VRC","VRD","VRE","VRG","VRP","VRT","VRV","VSB","VSC","VSD","VSE","VSG","VSP","VST","VSV","VTB","VTC","VTE","VTG","VTP","VTT","VTV","VTZ","VUB","VUC","VUE","VUP","VUT","VUV","VUZ","VVB","VVC","VVD","VVP","VVT","VVV","VVZ","VWC","VWD","VWG","VWP","VWT","VXB","VXC","VXD","VYP","VYT","VZC","VZT","VZV","WAB","WAC","WAD","WAE","WAG","WAP","WAT","WAV","WBB","WBC","WBD","WBE","WBG","WBP","WBT","WBZ","WCB","WCC","WCD","WCE","WCG","WCP","WCT","WCV","WDB","WDC","WDD","WDE","WDP","WDT","WDV","WDZ","WEB","WEC","WED","WEE","WEG","WEP","WET","WFB","WFC","WFD","WFE","WFG","WFP","WFT","WGB","WGC","WGD","WGP","WGT","WHB","WHC","WHD","WHE","WHP","WHT","WHV","WIB","WIC","WID","WIE","WIG","WIP","WIT","WIZ","WJB","WJC","WJT","WJZ","WKB","WKC","WKD","WKE","WKP","WKT","WLB","WLC","WLE","WLG","WLP","WLT","WMB","WMC","WMD","WME","WMG","WMP","WMT","WMV","WMZ","WNB","WNC","WND","WNP","WNT","WNV","WNZ","WOB","WOC","WOD","WOG","WOP","WOT","WOV","WOZ","WPB","WPC","WPD","WPE","WPG","WPP","WPT","WPZ","WQT","WRB","WRC","WRD","WRE","WRG","WRP","WRT","WSB","WSC","WSD","WSE","WSG","WSP","WST","WSV","WSZ","WTB","WTC","WTD","WTG","WTP","WTT","WTV","WTZ","WUB","WUC","WUD","WUG","WUP","WUT","WUZ","WVC","WVT","WWB","WWC","WWD","WWE","WWG","WWP","WWT","WWV","WWZ","WXC","WXP","WYB","WYD","WYG","WYP","WZB","WZC","WZP","WZT","XAB","XAC","XAD","XAG","XAP","XAT","XAV","XBC","XBE","XBG","XBP","XBT","XCB","XCD","XCP","XDB","XDC","XDE","XDG","XDP","XDT","XDV","XED","XEE","XEG","XEP","XET","XEV","XFC","XFD","XFG","XFP","XFT","XFV","XGB","XGE","XGG","XGP","XHD","XHP","XHT","XIB","XIC","XIE","XIP","XIT","XIV","XJP","XKB","XLB","XLD","XLT","XLV","XMB","XMC","XMD","XMG","XMP","XMT","XNT","XOC","XOG","XOP","XOT","XOV","XPB","XPC","XPD","XPE","XPG","XPP","XPT","XPV","XQD","XQP","XQT","XRC","XRD","XRP","XRT","XSB","XSC","XSD","XSE","XSP","XST","XSV","XTC","XTG","XTP","XTV","XUD","XUP","XUV","XUZ","XVG","XVT","XWD","XWP","XWT","XXB","XXC","XXP","XXV","XYP","XYZ","YAB","YAC","YAD","YAE","YAG","YAP","YAT","YAV","YAZ","YBB","YBC","YBD","YBE","YBG","YBP","YBT","YBV","YCB","YCC","YCD","YCE","YCG","YCP","YCT","YCV","YCZ","YDB","YDC","YDD","YDE","YDG","YDP","YDT","YDV","YEB","YEC","YED","YEE","YEG","YEV","YFB","YFC","YFD","YFE","YFG","YFP","YFT","YFZ","YGB","YGC","YGD","YGE","YGP","YGT","YGV","YGZ","YHB","YHC","YHD","YHE","YHG","YHP","YHT","YHZ","YIB","YIC","YID","YIE","YIG","YIP","YIT","YIV","YJB","YJC","YJT","YKC","YKG","YKP","YKZ","YLB","YLC","YLD","YLE","YLT","YMB","YMC","YMD","YME","YMG","YMP","YMT","YNB","YNC","YND","YNE","YNG","YNP","YNT","YNZ","YOB","YOC","YOD","YOG","YOP","YOT","YPB","YPC","YPD","YPE","YPG","YPP","YPT","YPZ","YQB","YQC","YQD","YQG","YQT","YQV","YQZ","YRB","YRC","YRD","YRG","YRP","YRT","YRV","YSB","YSC","YSE","YSG","YSP","YST","YSV","YSZ","YTB","YTC","YTD","YTE","YTP","YTT","YTV","YTZ","YUB","YUD","YUG","YUP","YUT","YUV","YVB","YVC","YVE","YVG","YVP","YVT","YVV","YVZ","YWB","YWC","YWG","YWP","YWV","YXC","YXD","YXE","YXP","YXT","YXZ","YYB","YYC","YYD","YYE","YYG","YYT","YYZ","YZD","YZE","YZG","YZP","YZT","YZV","YZZ","ZAB","ZAC","ZAD","ZAG","ZAP","ZAT","ZAZ","ZBB","ZBC","ZBT","ZCC","ZCE","ZCP","ZDC","ZDD","ZDE","ZDP","ZDT","ZDV","ZEB","ZEC","ZED","ZET","ZEV","ZFB","ZFC","ZFD","ZFP","ZFT","ZFV","ZGB","ZGC","ZGG","ZGZ","ZHP","ZHV","ZID","ZIG","ZIP","ZIZ","ZJG","ZKB","ZKC","ZKE","ZKG","ZKP","ZLC","ZLT","ZMB","ZMC","ZMD","ZME","ZMP","ZMT","ZMZ","ZNC","ZND","ZNE","ZNG","ZNP","ZNT","ZNZ","ZOB","ZOC","ZOE","ZOG","ZOP","ZPB","ZPC","ZPD","ZPE","ZPG","ZPP","ZPT","ZPZ","ZQZ","ZRB","ZRG","ZRP","ZSC","ZSE","ZSG","ZSP","ZST","ZSZ","ZTB","ZTC","ZTE","ZTG","ZTP","ZTT","ZTV","ZUC","ZUG","ZUZ","ZVE","ZVV","ZWC","ZWD","ZWE","ZWG","ZWT","ZWZ","ZXC","ZYZ","ZZT","ZZV","ZZZ" ]

ound_words = ['abound', 'aground', 'around', 'astound', 'bound', 'browned',
'compound', 'confound', 'confound', 'crowned', 'downed', 'drowned', 'expound',
'found', 'frowned', 'ground', 'hound', 'impound', 'inbound', 'mound',
'newfound', 'pound', 'profound', 'propound', 'rebound', 'redound', 'renowned',
'resound', 'resound', "'round", 'round', 'surround', 'ultrasound',
'unbound', 'unsound', 'unwound', 'wound']

tpl = "{tla} {ound}system"

def gen_str():
  while True:
    yield tpl.format(tla=choice(tlas), ound=choice(ound_words).title())

generator = gen_str()
